name: sinarsteel_mobile
description: Aplikasi Mobile SinarSteel (All-in-One)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  camera: ^0.10.5+9
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  intl: ^0.18.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^21.0.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true