"""all_tables

Revision ID: 1ef633b6ced8
Revises: 
Create Date: 2026-04-26 15:19:00.306792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef633b6ced8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('pelanggan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('limit_kredit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('saldo_kredit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('rack',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('lokasi', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('satuan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('supplier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('karyawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('tanggal_masuk', sa.Date(), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('gaji_pokok', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bpjs_tk', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bpjs_kes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('no_rek', sa.String(length=30), nullable=True),
    sa.Column('bank', sa.String(length=50), nullable=True),
    sa.Column('status_aktif', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('foto_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik')
    )
    op.create_table('produk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('kategori_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('satuan_id', sa.UUID(), nullable=True),
    sa.Column('harga_beli', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga_jual', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('stok_minimum', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('gambar_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.ForeignKeyConstraint(['satuan_id'], ['satuan.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produk_barcode'), 'produk', ['barcode'], unique=False)
    op.create_index(op.f('ix_produk_sku'), 'produk', ['sku'], unique=True)
    op.create_table('purchase_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('no_po', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('tanggal_order', sa.DateTime(), nullable=False),
    sa.Column('tanggal_diterima', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_po')
    )
    op.create_table('shift',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kasir_id', sa.UUID(), nullable=False),
    sa.Column('waktu_buka', sa.DateTime(), nullable=False),
    sa.Column('waktu_tutup', sa.DateTime(), nullable=True),
    sa.Column('total_transaksi', sa.Integer(), nullable=False),
    sa.Column('total_tunai', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_transfer', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_qris', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['kasir_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absensi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('karyawan_id', sa.UUID(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jam_masuk', sa.Time(), nullable=True),
    sa.Column('jam_pulang', sa.Time(), nullable=True),
    sa.Column('foto_masuk_url', sa.String(length=300), nullable=True),
    sa.Column('foto_pulang_url', sa.String(length=300), nullable=True),
    sa.Column('lat_masuk', sa.Float(), nullable=True),
    sa.Column('lon_masuk', sa.Float(), nullable=True),
    sa.Column('lat_pulang', sa.Float(), nullable=True),
    sa.Column('lon_pulang', sa.Float(), nullable=True),
    sa.Column('status_hadir', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gaji',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('karyawan_id', sa.UUID(), nullable=False),
    sa.Column('periode_bulan', sa.Integer(), nullable=False),
    sa.Column('periode_tahun', sa.Integer(), nullable=False),
    sa.Column('gaji_pokok', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tunjangan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lembur_jam', sa.Integer(), nullable=False),
    sa.Column('tarif_lembur', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_lembur', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('potongan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bpjs_tk', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bpjs_kes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_gaji', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_shift',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('karyawan_id', sa.UUID(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('shift_ke', sa.String(length=10), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=False),
    sa.Column('jam_selesai', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('produk_id', sa.UUID(), nullable=False),
    sa.Column('qty_order', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_mutation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produk_id', sa.UUID(), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('referensi', sa.String(length=100), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_opname',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('produk_id', sa.UUID(), nullable=False),
    sa.Column('qty_sistem', sa.Integer(), nullable=False),
    sa.Column('qty_fisik', sa.Integer(), nullable=False),
    sa.Column('selisih', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('no_transaksi', sa.String(length=30), nullable=False),
    sa.Column('kasir_id', sa.UUID(), nullable=False),
    sa.Column('pelanggan_id', sa.UUID(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('jenis_pembayaran', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_sebelum_diskon', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('diskon_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_setelah_diskon', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bayar', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('kembalian', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kasir_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pelanggan_id'], ['pelanggan.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_no_transaksi'), 'transaksi', ['no_transaksi'], unique=True)
    op.create_table('delivery_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('no_order', sa.String(length=30), nullable=False),
    sa.Column('transaksi_id', sa.UUID(), nullable=True),
    sa.Column('pelanggan_id', sa.UUID(), nullable=False),
    sa.Column('nama_penerima', sa.String(length=150), nullable=False),
    sa.Column('alamat_pengiriman', sa.Text(), nullable=False),
    sa.Column('kota', sa.String(length=100), nullable=False),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('nominal_cod', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['karyawan.id'], ),
    sa.ForeignKeyConstraint(['pelanggan_id'], ['pelanggan.id'], ),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_order')
    )
    op.create_table('transaksi_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaksi_id', sa.UUID(), nullable=False),
    sa.Column('produk_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('diskon_per_item', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_status_history')
    op.drop_table('transaksi_item')
    op.drop_table('delivery_order')
    op.drop_index(op.f('ix_transaksi_no_transaksi'), table_name='transaksi')
    op.drop_table('transaksi')
    op.drop_table('stock_opname')
    op.drop_table('stock_mutation')
    op.drop_table('purchase_order_item')
    op.drop_table('jadwal_shift')
    op.drop_table('gaji')
    op.drop_table('absensi')
    op.drop_table('shift')
    op.drop_table('purchase_order')
    op.drop_index(op.f('ix_produk_sku'), table_name='produk')
    op.drop_index(op.f('ix_produk_barcode'), table_name='produk')
    op.drop_table('produk')
    op.drop_table('karyawan')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('supplier')
    op.drop_table('satuan')
    op.drop_table('rack')
    op.drop_table('pelanggan')
    op.drop_table('kategori')
    # ### end Alembic commands ###
