"""add hpp_rata_rata to produk

Revision ID: 4dc80eb3ec63
Revises: 1ef633b6ced8
Create Date: 2026-04-29 20:16:54.700287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc80eb3ec63'
down_revision: Union[str, None] = '1ef633b6ced8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('hpp_rata_rata', sa.Numeric(precision=15, scale=2), nullable=False))
    op.alter_column('shift', 'saldo_awal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift', 'saldo_awal',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('produk', 'hpp_rata_rata')
    # ### end Alembic commands ###
