"""add void_pins and parent_id

Revision ID: c76133a16bc9
Revises: 6297cd724d77
Create Date: 2026-04-30 11:53:16.457494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76133a16bc9'
down_revision: Union[str, None] = '6297cd724d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('void_pins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaksi_id', sa.UUID(), nullable=False),
    sa.Column('pin', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('void_pins')
    # ### end Alembic commands ###
