"""add gaji_per_hari and tipe_gaji to karyawan

Revision ID: f35f4a3fbd9b
Revises: 64b9ac861a0e
Create Date: 2026-05-04 10:14:21.605781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35f4a3fbd9b'
down_revision: Union[str, None] = '64b9ac861a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('karyawan', sa.Column('gaji_per_hari', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('karyawan', sa.Column('tipe_gaji', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('karyawan', 'tipe_gaji')
    op.drop_column('karyawan', 'gaji_per_hari')
    # ### end Alembic commands ###
