"""make pelanggan_id nullable

Revision ID: fdf352d7f3be
Revises: c76133a16bc9
Create Date: 2026-04-30 13:54:12.919543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf352d7f3be'
down_revision: Union[str, None] = 'c76133a16bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_order', 'pelanggan_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_order', 'pelanggan_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
