import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Suspense, lazy } from 'react';
import { Routes, Route, Navigate } from 'react-router-dom';
import MainLayout from '../components/layout/MainLayout';
import ProtectedRoute from './ProtectedRoute';
import LoginPage from '../modules/auth/LoginPage';
import MasterLayout from '../modules/master/MasterLayout';
import ProdukList from '../modules/master/ProdukList';
import ProdukForm from '../modules/master/ProdukForm';
import SupplierList from '../modules/master/SupplierList';
import PelangganList from '../modules/master/PelangganList';
import WmsPage from '../modules/wms/WmsPage';
import InventoryList from '../modules/wms/InventoryList';
import StockOpnameList from '../modules/wms/StockOpnameList';
import MutationHistory from '../modules/wms/MutationHistory';
import HrPage from '../modules/hr/HrPage';
import KaryawanList from '../modules/hr/KaryawanList';
import JadwalShiftList from '../modules/hr/JadwalShiftList';
import AbsensiList from '../modules/hr/AbsensiList';
import GajiList from '../modules/hr/GajiList';
import DeliveryPage from '../modules/delivery/DeliveryPage';
import DeliveryOrderList from '../modules/delivery/DeliveryOrderList';
import SettingsPage from '../modules/settings/SettingsPage';
import KategoriSatuanList from '../modules/master/KategoriSatuanList';
import FinancePage from '../modules/finance/FinancePage';
import JournalList from '../modules/finance/JournalList';
import COAList from '../modules/finance/COAList';
import CashPage from '../modules/finance/CashPage';
import LedgerPage from '../modules/finance/LedgerPage';
import FinanceReportPage from '../modules/finance/ReportPage';
import TrialBalancePage from '../modules/finance/TrialBalancePage';
import UserList from '../modules/hr/UserList';
const DashboardPage = lazy(() => import('../modules/dashboard/DashboardPage'));
const PosPage = lazy(() => import('../modules/pos/PosPage'));
const ReportPage = lazy(() => import('../modules/report/ReportPage'));
const LoadingFallback = () => (_jsx("div", { className: "flex items-center justify-center h-full", children: _jsx("div", { className: "text-neon-cyan text-lg animate-pulse", children: "Loading..." }) }));
const AppRouter = () => (_jsx(Suspense, { fallback: _jsx(LoadingFallback, {}), children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsxs(Route, { element: _jsx(ProtectedRoute, { children: _jsx(MainLayout, {}) }), children: [_jsx(Route, { path: "/", element: _jsx(DashboardPage, {}) }), _jsxs(Route, { path: "/master", element: _jsx(MasterLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(Navigate, { to: "/master/produk", replace: true }) }), _jsx(Route, { path: "produk", element: _jsx(ProdukList, {}) }), _jsx(Route, { path: "produk/tambah", element: _jsx(ProdukForm, {}) }), _jsx(Route, { path: "produk/edit/:id", element: _jsx(ProdukForm, {}) }), _jsx(Route, { path: "supplier", element: _jsx(SupplierList, {}) }), _jsx(Route, { path: "pelanggan", element: _jsx(PelangganList, {}) }), _jsx(Route, { path: "kategori-satuan", element: _jsx(KategoriSatuanList, {}) })] }), _jsxs(Route, { path: "/wms", element: _jsx(WmsPage, {}), children: [_jsx(Route, { index: true, element: _jsx(InventoryList, {}) }), _jsx(Route, { path: "mutation", element: _jsx(MutationHistory, {}) }), _jsx(Route, { path: "inventory", element: _jsx(InventoryList, {}) }), _jsx(Route, { path: "opname", element: _jsx(StockOpnameList, {}) }), _jsx(Route, { path: "mutation", element: _jsx(MutationHistory, {}) })] }), _jsxs(Route, { path: "/hr", element: _jsx(HrPage, {}), children: [_jsx(Route, { index: true, element: _jsx(KaryawanList, {}) }), _jsx(Route, { path: "karyawan", element: _jsx(KaryawanList, {}) }), _jsx(Route, { path: "jadwal", element: _jsx(JadwalShiftList, {}) }), _jsx(Route, { path: "absensi", element: _jsx(AbsensiList, {}) }), _jsx(Route, { path: "gaji", element: _jsx(GajiList, {}) }), _jsx(Route, { path: "users", element: _jsx(UserList, {}) })] }), _jsxs(Route, { path: "/delivery", element: _jsx(DeliveryPage, {}), children: [_jsx(Route, { index: true, element: _jsx(DeliveryOrderList, {}) }), _jsx(Route, { path: "orders", element: _jsx(DeliveryOrderList, {}) })] }), _jsxs(Route, { path: "/finance", element: _jsx(FinancePage, {}), children: [_jsx(Route, { index: true, element: _jsx(JournalList, {}) }), _jsx(Route, { path: "journals", element: _jsx(JournalList, {}) }), _jsx(Route, { path: "coa", element: _jsx(COAList, {}) }), _jsx(Route, { path: "ledger", element: _jsx(LedgerPage, {}) }), _jsx(Route, { path: "cash", element: _jsx(CashPage, {}) }), _jsx(Route, { path: "reports", element: _jsx(FinanceReportPage, {}) }), _jsx(Route, { path: "trial-balance", element: _jsx(TrialBalancePage, {}) })] }), _jsx(Route, { path: "/pos", element: _jsx(PosPage, {}) }), _jsx(Route, { path: "/wms", element: _jsx(WmsPage, {}) }), _jsx(Route, { path: "/hr", element: _jsx(HrPage, {}) }), _jsx(Route, { path: "/delivery", element: _jsx(DeliveryPage, {}) }), _jsx(Route, { path: "/report", element: _jsx(ReportPage, {}) }), _jsx(Route, { path: "/settings", element: _jsx(SettingsPage, {}) })] }), _jsx(Route, { path: "*", element: _jsx(Navigate, { to: "/", replace: true }) })] }) }));
export default AppRouter;
